// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ConstructLayout: typeof import('./../components/Construct/Layout.vue')['default']
    ConstructLink: typeof import('./../components/Construct/Link.vue')['default']
    ConstructPage: typeof import('./../components/Construct/Page.vue')['default']
    DataCard: typeof import('./../components/Data/Card.vue')['default']
    DataCardTitle: typeof import('./../components/Data/CardTitle.vue')['default']
    DataCpu: typeof import('./../components/Data/Cpu.vue')['default']
    DataMemory: typeof import('./../components/Data/Memory.vue')['default']
    DataNetInterface: typeof import('./../components/Data/NetInterface.vue')['default']
    DataNetwork: typeof import('./../components/Data/Network.vue')['default']
    DataStatCard: typeof import('./../components/Data/StatCard.vue')['default']
    DataStorage: typeof import('./../components/Data/Storage.vue')['default']
    DataStorageVolume: typeof import('./../components/Data/StorageVolume.vue')['default']
    HelloWorld: typeof import('./../components/HelloWorld.vue')['default']
    NavigationMain: typeof import('./../components/Navigation/Main.vue')['default']
    ProgressBar: typeof import('./../components/ProgressBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatCard: typeof import('./../components/StatCard.vue')['default']
  }
}
